name: Release
on:
  push:
    tags:
      - 'v*.*.*'
env:
  TAG: "$(git rev-parse --short HEAD)"

jobs:
  clean_code_check:
    uses: ./.github/workflows/clean_code.yaml

  build_images:
    needs: clean_code_check
    uses: ./.github/workflows/build.yaml
    with:
      TAG: ${{ github.ref_name }}-${{ github.sha }}

  run_tests:
    needs: build_images
    uses: ./.github/workflows/test.yaml

  push_images:
    needs: run_tests
    uses: ./.github/workflows/push_artifacts.yaml
    with:
      TAG: ${{ github.ref_name }}-${{ github.sha }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
